# Generated by Django 5.2.16 on 2026-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('key', models.CharField(default='default', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('twilio_account_sid_secret', models.TextField(blank=True, editable=False)),
                ('twilio_api_key_sid_secret', models.TextField(blank=True, editable=False)),
                ('twilio_api_key_secret_secret', models.TextField(blank=True, editable=False)),
                ('twilio_auth_token_secret', models.TextField(blank=True, editable=False)),
                ('twilio_sms_from', models.CharField(blank=True, max_length=40, verbose_name='remetente SMS')),
                ('twilio_status_callback_url', models.URLField(blank=True, verbose_name='URL de estados Twilio')),
                ('mpesa_number', models.CharField(blank=True, max_length=40, verbose_name='número M-Pesa')),
                ('mpesa_account_name', models.CharField(blank=True, max_length=100, verbose_name='titular M-Pesa')),
                ('whatsapp_number', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp de pagamentos')),
            ],
            options={
                'verbose_name': 'configuração da plataforma',
                'verbose_name_plural': 'configuração da plataforma',
            },
        ),
    ]
