# Generated by Django 5.2.16 on 2026-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='payzeno_api_key_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='payzeno_base_url',
            field=models.URLField(default='https://api.payzeno.io', verbose_name='URL da API Payzeno'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='payzeno_enabled',
            field=models.BooleanField(default=False, verbose_name='activar pagamentos Payzeno'),
        ),
    ]
