# Generated by Django 5.2.17 on 2026-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_platformconfiguration_payzeno_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='payments_paused',
            field=models.BooleanField(default=False, help_text='Enquanto estiver activo, todos os eventos usam a plataforma sem subscrição: sem bloqueios de upgrade nem limites de convidados ou equipa.', verbose_name='pausar pagamentos'),
        ),
    ]
