# Generated by Django 5.2.16 on 2026-07-29 11:38

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='endereço')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='descrição')),
                ('map_url', models.URLField(blank=True, max_length=500, verbose_name='ligação do mapa')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone], verbose_name='telefone de contacto')),
                ('parking_information', models.TextField(blank=True, max_length=500, verbose_name='estacionamento')),
                ('transport_information', models.TextField(blank=True, max_length=500, verbose_name='transporte')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='weddings.wedding', verbose_name='casamento')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('religious', 'Cerimónia religiosa'), ('civil', 'Cerimónia civil'), ('reception', 'Recepção'), ('welcome_drink', 'Copo de água / Welcome drink'), ('photo_session', 'Sessão fotográfica'), ('cake_cutting', 'Corte do bolo'), ('lobolo', 'Lobolo'), ('xiguiane', 'Xiguiane'), ('traditional', 'Cerimónia tradicional'), ('custom', 'Outro evento')], default='custom', max_length=30, verbose_name='tipo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=70, verbose_name='identificador')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='descrição')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de fim')),
                ('map_url', models.URLField(blank=True, max_length=500, verbose_name='ligação do mapa')),
                ('host_family', models.CharField(blank=True, help_text='Por exemplo, a família que recebe o lobolo ou o xiguiane.', max_length=150, verbose_name='família anfitriã')),
                ('dress_code', models.CharField(blank=True, max_length=150, verbose_name='traje')),
                ('instructions', models.TextField(blank=True, max_length=2000, verbose_name='instruções aos convidados')),
                ('requires_rsvp', models.BooleanField(default=True, verbose_name='exige confirmação')),
                ('requires_qr_code', models.BooleanField(default=False, verbose_name='exige QR Code à entrada')),
                ('show_to_all_guests', models.BooleanField(default=True, help_text='Se desactivado, só os convidados autorizados vêem este evento.', verbose_name='visível para todos os convidados')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='weddings.wedding', verbose_name='casamento')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.weddinglocation', verbose_name='local')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['date', 'start_time', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('date', models.DateField(blank=True, null=True, verbose_name='data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de fim')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone Bootstrap, por exemplo bi-camera.', max_length=40, verbose_name='ícone')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem')),
                ('is_public', models.BooleanField(default=True, help_text='Se desactivado, aparece apenas nos convites individuais.', verbose_name='visível na página pública')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='weddings.wedding', verbose_name='casamento')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='events.weddingevent', verbose_name='evento')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='events.weddinglocation', verbose_name='local')),
            ],
            options={
                'verbose_name': 'item do programa',
                'verbose_name_plural': 'programa',
                'ordering': ['display_order', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='weddinglocation',
            index=models.Index(fields=['wedding', 'display_order'], name='location_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='weddinglocation',
            constraint=models.UniqueConstraint(fields=('wedding', 'name'), name='unique_location_name_per_wedding'),
        ),
        migrations.AddIndex(
            model_name='weddingevent',
            index=models.Index(fields=['wedding', 'is_active'], name='event_wedding_active_idx'),
        ),
        migrations.AddIndex(
            model_name='weddingevent',
            index=models.Index(fields=['wedding', 'date', 'start_time'], name='event_wedding_when_idx'),
        ),
        migrations.AddConstraint(
            model_name='weddingevent',
            constraint=models.UniqueConstraint(fields=('wedding', 'name'), name='unique_event_name_per_wedding'),
        ),
        migrations.AddConstraint(
            model_name='weddingevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('start_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['wedding', 'display_order'], name='schedule_order_idx'),
        ),
    ]
