# Generated by Django 5.2.16 on 2026-07-30 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('icon', models.CharField(default='bi-calendar-heart', help_text='Nome do ícone Bootstrap, por exemplo bi-cake2.', max_length=40, verbose_name='ícone')),
                ('uses_two_names', models.BooleanField(default=False, help_text='Um casamento tem dois nomes; um aniversário tem um.', verbose_name='dois protagonistas')),
                ('primary_label', models.CharField(default='Nome', max_length=60, verbose_name='etiqueta do 1.º nome')),
                ('secondary_label', models.CharField(blank=True, max_length=60, verbose_name='etiqueta do 2.º nome')),
                ('names_separator', models.CharField(default='&', help_text='Usado no título: «Ivone & Dário».', max_length=10, verbose_name='separador dos nomes')),
                ('field_schema', models.JSONField(blank=True, default=list, help_text='Lista de campos extra. Exemplo: [{"key": "idade", "label": "Idade a celebrar", "type": "number"}]. Tipos aceites: text, textarea, number, date.', verbose_name='campos próprios')),
                ('default_moments', models.JSONField(blank=True, default=list, help_text='Momentos criados automaticamente. Exemplo: [{"name": "Recepção", "event_type": "reception", "start_time": "19:30"}]', verbose_name='momentos predefinidos')),
                ('default_schedule', models.JSONField(blank=True, default=list, help_text='Exemplo: [{"title": "Corte do bolo", "start_time": "18:30", "icon": "bi-cake2"}]', verbose_name='programa predefinido')),
                ('invitation_greeting', models.CharField(default='tem o prazer de o convidar para', help_text='Usada no convite, depois dos nomes dos protagonistas.', max_length=200, verbose_name='frase do convite')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'tipo de evento',
                'verbose_name_plural': 'tipos de evento',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='campos adicionais'),
        ),
    ]
