# Generated by Django 5.2.16 on 2026-07-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_batizado_to_batismo'),
        ('weddings', '0003_alter_weddingmember_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='weddings.wedding', verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='weddingevent',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='weddings.wedding', verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='weddinglocation',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='weddings.wedding', verbose_name='evento'),
        ),
    ]
