# Generated by Django 5.2.16 on 2026-07-29 11:38

import accounts.managers
import core.storage
import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='nome próprio')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apelido')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone], verbose_name='telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.storage.user_avatar_upload_to, validators=[core.validators.validate_image_upload], verbose_name='fotografia')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite o acesso à administração da plataforma.', verbose_name='equipa MeuConvite')),
                ('preferred_language', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], default='pt', max_length=5, verbose_name='idioma')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='último IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilizador',
                'verbose_name_plural': 'utilizadores',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
