# Generated by Django 5.2.16 on 2026-07-31 08:56

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_scheduleitem_wedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descrição')),
                ('layout', models.CharField(choices=[('carta_selada', 'Carta selada (abertura animada)'), ('envelope_botanico', 'Envelope botânico'), ('cartao_classico', 'Cartão clássico')], default='cartao_classico', help_text='A estrutura da página do convite.', max_length=40, verbose_name='layout')),
                ('primary', models.CharField(default='#C8A96A', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor principal')),
                ('secondary', models.CharField(default='#1F2933', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor secundária')),
                ('paper', models.CharField(default='#FFFDF8', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor do papel')),
                ('ink', models.CharField(default='#3A3226', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor do texto')),
                ('display_font', models.CharField(default='"Great Vibes", cursive', help_text='Valor CSS, por exemplo: "Playfair Display", Georgia, serif', max_length=120, verbose_name='letra dos títulos')),
                ('body_font', models.CharField(default='"Cormorant Garamond", Georgia, serif', max_length=120, verbose_name='letra do texto')),
                ('google_fonts', models.CharField(blank=True, help_text='Parâmetros family= a carregar, separados por «|». Exemplo: Great+Vibes|Cormorant+Garamond:wght@400;600', max_length=250, verbose_name='famílias do Google Fonts')),
                ('has_cover', models.BooleanField(default=True, help_text='Mostra um ecrã de abertura antes do convite.', verbose_name='abertura com capa')),
                ('has_countdown', models.BooleanField(default=True, verbose_name='contagem regressiva')),
                ('supports_music', models.BooleanField(default=True, verbose_name='suporta música')),
                ('preview_image', models.ImageField(blank=True, help_text='Opcional: a pré-visualização é gerada a partir do próprio layout.', null=True, upload_to='templates/previews/', validators=[core.validators.validate_image_upload], verbose_name='imagem de pré-visualização')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgulas: clássico, dourado, floral…', max_length=150, verbose_name='etiquetas')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece primeiro na escolha do template.', verbose_name='destaque')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('categories', models.ManyToManyField(blank=True, help_text='Deixe vazio para o template servir todos os tipos de evento.', related_name='invitation_templates', to='events.eventcategory', verbose_name='tipos de evento')),
            ],
            options={
                'verbose_name': 'template de convite',
                'verbose_name_plural': 'templates de convite',
                'ordering': ['-is_featured', 'display_order', 'name'],
            },
        ),
    ]
