# Generated by Django 5.2.16 on 2026-07-29 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, help_text='Guardado em texto para o registo sobreviver à remoção da conta.', max_length=160, verbose_name='identificação do autor')),
                ('action', models.CharField(choices=[('login', 'Início de sessão'), ('login_failed', 'Tentativa de início de sessão falhada'), ('logout', 'Fim de sessão'), ('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Eliminação'), ('publish', 'Publicação'), ('invite_sent', 'Convite enviado'), ('invite_revoked', 'Convite revogado'), ('rsvp_submitted', 'Confirmação submetida'), ('checkin', 'Check-in'), ('checkin_override', 'Check-in com autorização especial'), ('import', 'Importação'), ('export', 'Exportação'), ('member_added', 'Membro adicionado'), ('member_removed', 'Membro removido'), ('permission_changed', 'Permissões alteradas'), ('admin_action', 'Operação administrativa')], db_index=True, max_length=40, verbose_name='acção')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='objecto')),
                ('object_label', models.CharField(blank=True, max_length=200, verbose_name='descrição do objecto')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='dados anteriores')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='dados novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='agente')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
                ('wedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='weddings.wedding', verbose_name='casamento')),
            ],
            options={
                'verbose_name': 'registo de auditoria',
                'verbose_name_plural': 'registos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wedding', '-created_at'], name='audit_wedding_date_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_date_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
