# Generated by Django 5.2.16 on 2026-08-01 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_invitation_and_rsvp'),
        ('weddings', '0006_wedding_invitation_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'A preparar'), ('queued', 'Na fila'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou'), ('undelivered', 'Não entregue'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('destination', models.CharField(max_length=40)),
                ('message_body', models.TextField(max_length=1600)),
                ('provider', models.CharField(default='twilio', max_length=30)),
                ('provider_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_deliveries', to='guests.guest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_deliveries_sent', to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_deliveries', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'envio de convite',
                'verbose_name_plural': 'envios de convites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest', '-created_at'], name='guest_delivery_date_idx'), models.Index(fields=['wedding', 'status'], name='wedding_delivery_status_idx')],
            },
        ),
    ]
