# Generated by Django 5.2.16 on 2026-08-01 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_invitationdelivery'),
        ('weddings', '0008_alter_wedding_sms_invitation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=160, verbose_name='presente')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='descrição')),
                ('allow_multiple', models.BooleanField(default=False, help_text='Por omissão, o presente fica reservado ao primeiro convidado.', verbose_name='permitir vários convidados')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'presente',
                'verbose_name_plural': 'presentes',
                'ordering': ['display_order', 'created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftSelection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='guests.gift')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_selections', to='guests.guest')),
            ],
            options={
                'verbose_name': 'selecção de presente',
                'verbose_name_plural': 'selecções de presentes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['wedding', 'is_active'], name='gift_wedding_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftselection',
            constraint=models.UniqueConstraint(fields=('gift', 'guest'), name='unique_gift_guest'),
        ),
    ]
