# Generated by Django 5.2.16 on 2026-08-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_compact_invitation_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='plan_access',
            field=models.BooleanField(blank=True, db_index=True, default=None, help_text='Sem valor usa a ordem automática; sim inclui e não exclui explicitamente.', null=True, verbose_name='incluído no plano'),
        ),
    ]
