# Generated by Django 5.2.16 on 2026-08-02 19:45

from django.db import migrations, models


def preserve_existing_full_programme_access(apps, schema_editor):
    """A selecção vazia antiga significava acesso total; materializa-a."""
    Guest = apps.get_model("guests", "Guest")
    WeddingEvent = apps.get_model("events", "WeddingEvent")
    Through = Guest.allowed_events.through

    wedding_ids = Guest.objects.values_list("wedding_id", flat=True).distinct()
    for wedding_id in wedding_ids.iterator():
        event_ids = list(
            WeddingEvent.objects.filter(wedding_id=wedding_id, is_active=True)
            .values_list("pk", flat=True)
        )
        if not event_ids:
            continue
        unrestricted_guest_ids = list(
            Guest.objects.filter(wedding_id=wedding_id, allowed_events__isnull=True)
            .values_list("pk", flat=True)
        )
        Through.objects.bulk_create(
            [
                Through(guest_id=guest_id, weddingevent_id=event_id)
                for guest_id in unrestricted_guest_ids
                for event_id in event_ids
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_formatura_display_to_graduacao'),
        ('guests', '0007_guest_plan_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='seating_assignment',
            field=models.CharField(blank=True, help_text='Ex.: Mesa dos Jacarandás, Mesa 8 ou Cadeira A12.', max_length=100, verbose_name='mesa ou cadeira'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='allowed_events',
            field=models.ManyToManyField(blank=True, help_text='Seleccione os momentos que este convidado pode consultar.', related_name='invited_guests', to='events.weddingevent', verbose_name='programa autorizado'),
        ),
        migrations.RunPython(
            preserve_existing_full_programme_access,
            migrations.RunPython.noop,
        ),
    ]
