# Generated by Django 5.2.17 on 2026-08-11 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_guest_seating_assignment_alter_guest_allowed_events'),
        ('weddings', '0018_wedding_invitation_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReminderDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='data do evento')),
                ('days_before', models.PositiveSmallIntegerField(verbose_name='dias de antecedência')),
                ('destination', models.EmailField(max_length=254, verbose_name='destino')),
                ('subject', models.CharField(max_length=255, verbose_name='assunto')),
                ('status', models.CharField(choices=[('pending', 'A preparar'), ('queued', 'Na fila'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou'), ('undelivered', 'Não entregue'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='guests.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'lembrete de evento',
                'verbose_name_plural': 'lembretes de eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wedding', 'event_date'], name='reminder_wedding_date_idx'), models.Index(fields=['status', 'created_at'], name='reminder_status_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('guest', 'event_date', 'days_before'), name='unique_guest_event_reminder')],
            },
        ),
    ]
