# Generated by Django 5.2.17 on 2026-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_eventreminderdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationdelivery',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationdelivery',
            name='destination',
            field=models.CharField(max_length=254),
        ),
    ]
