# Generated by Django 5.2.16 on 2026-07-30 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0002_alter_wedding_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('max_guests', models.PositiveIntegerField(help_text='Número máximo de convidados por evento.', verbose_name='convidados incluídos')),
                ('max_events', models.PositiveIntegerField(default=1, help_text='Quantos eventos o utilizador pode ter em simultâneo.', verbose_name='eventos incluídos')),
                ('price_mzn', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço (MZN)')),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='Quanto tempo a subscrição fica activa depois de confirmada.', verbose_name='duração (dias)')),
                ('allows_qr_checkin', models.BooleanField(default=False, verbose_name='check-in com QR Code')),
                ('allows_seating', models.BooleanField(default=False, verbose_name='gestão de mesas')),
                ('allows_team', models.BooleanField(default=False, verbose_name='equipa')),
                ('allows_exports', models.BooleanField(default=False, verbose_name='exportações')),
                ('removes_branding', models.BooleanField(default=False, verbose_name='sem marca MeuConvite')),
                ('templates_limit', models.PositiveIntegerField(default=1, help_text='0 = todos os templates.', verbose_name='templates disponíveis')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('is_default', models.BooleanField(default=False, help_text='O plano atribuído automaticamente a cada evento novo.', verbose_name='plano inicial')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['display_order', 'max_guests'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'À espera de confirmação de pagamento'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=20, verbose_name='estado')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='início')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('guest_allowance', models.PositiveIntegerField(verbose_name='convidados permitidos')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='plano')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='weddings.wedding', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'subscrição',
                'verbose_name_plural': 'subscrições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, help_text='Código que o utilizador indica ao enviar o comprovativo.', max_length=20, unique=True, verbose_name='referência')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('bank_transfer', 'Transferência bancária'), ('other', 'Outro')], default='mpesa', max_length=20, verbose_name='método')),
                ('amount_mzn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montante (MZN)')),
                ('paid_to', models.CharField(blank=True, help_text='Número ou conta que recebeu o pagamento.', max_length=40, verbose_name='pago para')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone de quem pagou')),
                ('transaction_id', models.CharField(blank=True, help_text='Código que o M-Pesa envia por SMS.', max_length=60, verbose_name='ID da transacção')),
                ('proof', models.FileField(blank=True, help_text='Opcional: o comprovativo também pode ser enviado por WhatsApp.', null=True, upload_to='payments/%Y/%m/', verbose_name='comprovativo')),
                ('status', models.CharField(choices=[('awaiting_proof', 'À espera do comprovativo'), ('under_review', 'Em verificação'), ('confirmed', 'Confirmado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], db_index=True, default='awaiting_proof', max_length=20, verbose_name='estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('review_notes', models.CharField(blank=True, max_length=300, verbose_name='notas da verificação')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='weddings.wedding', verbose_name='evento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payment_status_date_idx'), models.Index(fields=['wedding', '-created_at'], name='payment_wedding_date_idx')],
            },
        ),
    ]
