# Generated by Django 5.2.16 on 2026-08-01 13:22

from django.db import migrations, models


def update_plan_limits(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Subscription = apps.get_model("subscriptions", "Subscription")
    sms_limits = {
        "gratuito": 2,
        "essencial-50": 50,
        "celebracao-100": 150,
        "premium-200": 400,
        "grande-evento-500": 1000,
    }
    for plan in Plan.objects.all():
        if plan.code == "gratuito" or plan.is_default and plan.price_mzn <= 0:
            plan.max_guests = 5
            plan.templates_limit = 1
        plan.max_sms = sms_limits.get(plan.code, max(plan.max_guests, 0))
        plan.save(update_fields=["max_guests", "max_sms", "templates_limit"])
        Subscription.objects.filter(plan=plan).update(
            guest_allowance=plan.max_guests,
            sms_allowance=plan.max_sms,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_sms',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de convites por SMS em cada evento.', verbose_name='SMS incluídos'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sms_allowance',
            field=models.PositiveIntegerField(default=0, help_text='Limite guardado no momento em que a subscrição é activada.', verbose_name='SMS permitidos'),
        ),
        migrations.RunPython(update_plan_limits, migrations.RunPython.noop),
    ]
