# Generated by Django 5.2.16 on 2026-08-02 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_disable_free_sms'),
        ('weddings', '0015_weddinggalleryphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descrição')),
                ('max_guests', models.PositiveIntegerField(verbose_name='limite de convidados')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='activar envio por SMS')),
                ('max_sms', models.PositiveIntegerField(default=0, verbose_name='limite de SMS')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='válido desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('max_redemptions', models.PositiveIntegerField(default=1, help_text='0 permite utilizações ilimitadas.', verbose_name='número máximo de utilizações')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_allowance', models.PositiveIntegerField(verbose_name='convidados concedidos')),
                ('sms_allowance', models.PositiveIntegerField(default=0, verbose_name='SMS concedidos')),
                ('redeemed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='aplicado por')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='subscriptions.voucher', verbose_name='voucher')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemption', to='weddings.wedding', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'utilização de voucher',
                'verbose_name_plural': 'utilizações de vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
