# Generated by Django 5.2.16 on 2026-08-02 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_voucher_voucherredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('payzeno', 'Payzeno')], db_index=True, default='manual', max_length=20, verbose_name='processador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processador verificado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='checkout do processador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_checkout_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='URL do checkout'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='checkout expira em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados do processador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='pagamento do processador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='estado no processador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_gateway', 'A aguardar pagamento'), ('awaiting_proof', 'À espera do comprovativo'), ('under_review', 'Em verificação'), ('confirmed', 'Confirmado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado'), ('chargeback', 'Contestado')], db_index=True, default='awaiting_proof', max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='payzeno', max_length=20)),
                ('event_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('checkout_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.CharField(blank=True, max_length=240)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
