# Generated by Django 5.2.16 on 2026-07-29 11:38

import core.storage
import core.utils
import core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bride_full_name', models.CharField(max_length=150, verbose_name='nome completo da noiva')),
                ('groom_full_name', models.CharField(max_length=150, verbose_name='nome completo do noivo')),
                ('bride_short_name', models.CharField(max_length=60, verbose_name='nome curto da noiva')),
                ('groom_short_name', models.CharField(max_length=60, verbose_name='nome curto do noivo')),
                ('slug', models.SlugField(help_text='Usado em meuconvite.co.mz/o-seu-endereco/', max_length=70, unique=True, validators=[core.validators.validate_wedding_slug], verbose_name='endereço público')),
                ('public_token', models.CharField(default=core.utils.generate_secure_token, editable=False, help_text='Token seguro usado em ligações que não devem expor o endereço.', max_length=64, unique=True, verbose_name='token público')),
                ('main_date', models.DateField(db_index=True, verbose_name='data principal')),
                ('timezone', models.CharField(default='Africa/Maputo', max_length=50, verbose_name='fuso horário')),
                ('country', models.CharField(default='Moçambique', max_length=80, verbose_name='país')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.storage.wedding_cover_upload_to, validators=[core.validators.validate_image_upload], verbose_name='fotografia de capa')),
                ('welcome_message', models.TextField(blank=True, max_length=1000, verbose_name='mensagem de boas-vindas')),
                ('story', models.TextField(blank=True, max_length=5000, verbose_name='a nossa história')),
                ('hashtag', models.CharField(blank=True, max_length=60, verbose_name='hashtag')),
                ('primary_color', models.CharField(default='#C8A96A', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor principal')),
                ('secondary_color', models.CharField(default='#1F2933', max_length=7, validators=[core.validators.validate_hex_color], verbose_name='cor secundária')),
                ('selected_template', models.CharField(default='classic', help_text='Identificador do template visual escolhido.', max_length=50, verbose_name='template')),
                ('invitation_music', models.FileField(blank=True, null=True, upload_to=core.storage.wedding_music_upload_to, validators=[core.validators.validate_audio_upload], verbose_name='música do convite')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado'), ('blocked', 'Bloqueado')], db_index=True, default='draft', max_length=20, verbose_name='estado')),
                ('show_music', models.BooleanField(default=False, verbose_name='reproduzir música')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='mostrar contagem regressiva')),
                ('show_seat_before_event', models.CharField(choices=[('always', 'Mostrar sempre no convite'), ('on_event_day', 'Mostrar apenas no dia do evento'), ('after_checkin', 'Mostrar depois do check-in'), ('never', 'Não mostrar no convite')], default='on_event_day', max_length=20, verbose_name='visibilidade da mesa')),
                ('rsvp_deadline', models.DateField(blank=True, null=True, verbose_name='prazo de confirmação')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('blocked_reason', models.CharField(blank=True, max_length=200, verbose_name='motivo do bloqueio')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_weddings', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'casamento',
                'verbose_name_plural': 'casamentos',
                'ordering': ['-main_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('spouse', 'Noivo(a)'), ('wedding_planner', 'Wedding planner'), ('committee', 'Comissão'), ('receptionist', 'Recepção'), ('viewer', 'Consulta')], default='committee', max_length=20, verbose_name='função')),
                ('can_manage_guests', models.BooleanField(default=False, verbose_name='gerir convidados')),
                ('can_manage_events', models.BooleanField(default=False, verbose_name='gerir eventos')),
                ('can_manage_seating', models.BooleanField(default=False, verbose_name='gerir mesas')),
                ('can_check_in', models.BooleanField(default=False, verbose_name='fazer check-in')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='ver relatórios')),
                ('can_manage_design', models.BooleanField(default=False, verbose_name='gerir design')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='gerir subscrição')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='convidado em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceite em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='weddings.wedding', verbose_name='casamento')),
            ],
            options={
                'verbose_name': 'membro da equipa',
                'verbose_name_plural': 'membros da equipa',
                'ordering': ['role', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wedding',
            index=models.Index(fields=['owner', 'status'], name='wedding_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wedding',
            index=models.Index(fields=['main_date'], name='wedding_main_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='wedding',
            constraint=models.CheckConstraint(condition=models.Q(('bride_full_name', ''), _negated=True), name='wedding_bride_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='wedding',
            constraint=models.CheckConstraint(condition=models.Q(('groom_full_name', ''), _negated=True), name='wedding_groom_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='weddingmember',
            index=models.Index(fields=['wedding', 'is_active'], name='member_wedding_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='weddingmember',
            constraint=models.UniqueConstraint(fields=('wedding', 'user'), name='unique_member_per_wedding'),
        ),
    ]
