# Generated by Django 5.2.16 on 2026-07-30 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcategory_scheduleitem_extra_data'),
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ['-main_date', '-created_at'], 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.RemoveConstraint(
            model_name='wedding',
            name='wedding_bride_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='wedding',
            name='wedding_groom_name_not_empty',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='bride_full_name',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='bride_short_name',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='groom_full_name',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='groom_short_name',
        ),
        migrations.AddField(
            model_name='wedding',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weddings', to='events.eventcategory', verbose_name='tipo de evento'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='dados específicos'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='primary_name',
            field=models.CharField(default='', max_length=150, verbose_name='nome completo (1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='primary_short_name',
            field=models.CharField(default='', max_length=60, verbose_name='nome curto (1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='schedule_field_schema',
            field=models.JSONField(blank=True, default=list, verbose_name='campos adicionais do programa'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome completo (2)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='secondary_short_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='nome curto (2)'),
        ),
        migrations.AddConstraint(
            model_name='wedding',
            constraint=models.CheckConstraint(condition=models.Q(('primary_name', ''), _negated=True), name='event_primary_name_not_empty'),
        ),
    ]
