# Generated by Django 5.2.16 on 2026-07-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_alter_wedding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingmember',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='weddings.wedding', verbose_name='evento'),
        ),
    ]
