# Generated by Django 5.2.16 on 2026-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_alter_weddingmember_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='selected_template',
            field=models.CharField(default='carta-selada', help_text='Código do template escolhido (templates_manager.InvitationTemplate).', max_length=50, verbose_name='template'),
        ),
    ]
