# Generated by Django 5.2.16 on 2026-08-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0006_wedding_invitation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='sms_invitation_message',
            field=models.CharField(default='Olá {nome}! {evento} convidam-no(a). Veja e confirme: {link}', help_text='Pode usar {nome}, {evento} e {link}.', max_length=500, verbose_name='mensagem do convite por SMS'),
        ),
    ]
