# Generated by Django 5.2.16 on 2026-08-01 13:55

from django.db import migrations, models


def refresh_untouched_sms_messages(apps, schema_editor):
    Wedding = apps.get_model("weddings", "Wedding")
    old_default = "Olá {nome}! {evento} convidam-no(a). Veja e confirme: {link}"
    new_default = (
        "Olá {nome}! 💌 É com muita alegria que partilhamos contigo o convite de {evento}. "
        "Abre o teu convite e confirma a tua presença: {link}"
    )
    Wedding.objects.filter(sms_invitation_message=old_default).update(
        sms_invitation_message=new_default
    )


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_wedding_sms_invitation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='sms_invitation_message',
            field=models.CharField(default='Olá {nome}! 💌 É com muita alegria que partilhamos contigo o convite de {evento}. Abre o teu convite e confirma a tua presença: {link}', help_text='Pode usar {nome}, {evento} e {link}.', max_length=500, verbose_name='mensagem do convite por SMS'),
        ),
        migrations.RunPython(refresh_untouched_sms_messages, migrations.RunPython.noop),
    ]
