# Generated by Django 5.2.16 on 2026-08-02 18:37

import core.storage
import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0014_enable_music_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingGalleryPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.storage.wedding_gallery_upload_to, validators=[core.validators.validate_image_upload], verbose_name='fotografia')),
                ('external_url', models.URLField(blank=True, help_text='Usado apenas pelas fotografias editoriais de demonstração.', max_length=500, verbose_name='endereço externo')),
                ('caption', models.CharField(blank=True, help_text='Aparece sobre a fotografia quando a galeria é aberta.', max_length=240, verbose_name='descrição')),
                ('credit_name', models.CharField(blank=True, max_length=120, verbose_name='crédito')),
                ('credit_url', models.URLField(blank=True, max_length=500, verbose_name='ligação do crédito')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='visível no convite')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='weddings.wedding', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'fotografia da galeria',
                'verbose_name_plural': 'fotografias da galeria',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['wedding', 'is_visible', 'display_order'], name='gallery_wed_visible_order_idx')],
            },
        ),
    ]
