# Generated by Django 5.2.16 on 2026-08-07 11:33

import core.storage
import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0016_wedding_whatsapp_invitation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('artist', models.CharField(blank=True, max_length=180, verbose_name='artista')),
                ('file', models.FileField(upload_to=core.storage.music_track_upload_to, validators=[core.validators.validate_audio_upload], verbose_name='ficheiro')),
                ('is_default', models.BooleanField(default=False, verbose_name='música padrão')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='disponível')),
                ('display_order', models.PositiveIntegerField(default=100, verbose_name='posição')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_music_tracks', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
            ],
            options={
                'verbose_name': 'música',
                'verbose_name_plural': 'músicas',
                'ordering': ['display_order', 'artist', 'title'],
            },
        ),
        migrations.AddField(
            model_name='wedding',
            name='invitation_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='weddings.musictrack', verbose_name='música escolhida'),
        ),
        migrations.AddIndex(
            model_name='musictrack',
            index=models.Index(fields=['is_active', 'display_order'], name='music_active_order_idx'),
        ),
    ]
