# Generated by Django 5.2.17 on 2026-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0022_wedding_story_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='invitation_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Textos personalizados do convite ({chave: texto}). Chaves e textos originais em weddings/invitation_texts.py; em branco usa-se o original.', verbose_name='textos do convite'),
        ),
    ]
